# Generated by Django 4.2.30 on 2026-08-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_update_ai_fluency_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hero_image',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='DailyChallengeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_email_deliveries', to='learning.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_email_deliveries', to='learning.lesson')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailychallengeemail',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson'), name='unique_daily_challenge_email_per_lesson'),
        ),
    ]
