# Generated by Django 4.2.30 on 2026-08-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_lesson_hero_image_dailychallengeemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
