# Generated by Django 5.2.11 on 2026-03-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-attempt__started_at']},
        ),
        migrations.RemoveConstraint(
            model_name='option',
            name='unique_question_option_order',
        ),
        migrations.RemoveField(
            model_name='attemptanswer',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='option',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='result',
            name='created_at',
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_timed_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=480),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='attempt_answers', to='quiz.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('SINGLE', 'Single Select'), ('MULTI', 'Multi Select')], default='SINGLE', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='multi_select_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='result',
            name='percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
