# Generated by Django 5.2.11 on 2026-03-03 15:58

from django.db import migrations, models
from django.db.models import Q
from django.utils.text import slugify


def populate_quiz_slugs(apps, schema_editor):
    Quiz = apps.get_model("quiz", "Quiz")
    existing = set(Quiz.objects.exclude(slug__isnull=True).exclude(slug="").values_list("slug", flat=True))
    for quiz in Quiz.objects.filter(Q(slug__isnull=True) | Q(slug="")):
        base = slugify(quiz.title) or "quiz-%s" % quiz.id
        candidate = base
        index = 1
        while candidate in existing:
            candidate = "%s-%s" % (base, index)
            index += 1
        quiz.slug = candidate
        quiz.save(update_fields=["slug"])
        existing.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_option_options_alter_quiz_options_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_quiz_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
