# Generated by Django 5.2.11 on 2026-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_result_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=1800),
        ),
    ]
