# Generated by Django 5.2.11 on 2026-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_attempt_time_limit_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AlterField(
            model_name='result',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Proficient', 'Proficient'), ('Advanced', 'Advanced'), ('Elite', 'Elite')], max_length=20),
        ),
    ]
