# Generated by Django 4.2.28 on 2026-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_attempt_time_taken_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="time_limit_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
