# Generated by Django 5.2.11 on 2026-03-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcampinterest',
            name='ai_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Proficient', 'Proficient'), ('Advanced', 'Advanced'), ('Elite', 'Elite')], max_length=20),
        ),
    ]
