# Generated by Django 4.2.28 on 2026-03-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bootcamp", "0002_alter_bootcampinterest_ai_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bootcampinterest",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("IN_PERSON", "In Person"),
                    ("BOOTCAMP", "Bootcamp"),
                ],
                max_length=20,
            ),
        ),
    ]
