# Generated by Django 5.2.11 on 2026-03-04 07:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0002_courseattempt_finalquizquestion_finalquizoption_and_more'),
        ('quiz', '0007_attempt_time_taken_seconds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AILiteracyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('deep_quiz_score', models.PositiveSmallIntegerField(default=0)),
                ('final_test_score', models.PositiveSmallIntegerField(default=0)),
                ('microcourse_completed', models.BooleanField(default=False)),
                ('ali_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Emerging', 'Emerging'), ('AI Practitioner', 'AI Practitioner'), ('AI Fluent', 'AI Fluent'), ('AI Leader', 'AI Leader')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ali_scores', to='learning.courseattempt')),
                ('deep_quiz_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ali_score', to='quiz.result')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_literacy_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
