import Link from "next/link";
import { credentialsLoginAction, googleSignInAction } from "@/app/actions/auth";
import { Button } from "@/components/ui/button";
import { RecaptchaWidget } from "@/components/auth/recaptcha-widget";

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ next?: string; error?: string }> }) {
  const params = await searchParams;
  const googleEnabled = Boolean(process.env.AUTH_GOOGLE_ID && process.env.AUTH_GOOGLE_SECRET);
  return <><p className="eyebrow">Welcome back</p><h1 className="display mt-3 text-5xl">Keep your momentum.</h1><p className="mb-8 mt-4 leading-7 text-[#5f6f67]">Sign in to continue your challenge and protect your streak.</p>{googleEnabled && <><form action={googleSignInAction}><input type="hidden" name="next" value={params.next ?? "/dashboard"} /><Button type="submit" variant="secondary" size="lg" className="w-full bg-white"><span aria-hidden="true" className="mr-3 grid size-6 place-items-center rounded-full border border-[#cad4ce] font-serif text-sm font-black text-[#123c31]">G</span>Continue with Google</Button></form><div className="my-6 flex items-center gap-3 text-xs font-bold uppercase tracking-widest text-[#839189]"><span className="h-px flex-1 bg-[#dce2dd]" />or use email<span className="h-px flex-1 bg-[#dce2dd]" /></div></>}<form action={credentialsLoginAction} className="grid gap-4"><input type="hidden" name="next" value={params.next ?? "/dashboard"} /><label className="grid gap-2 text-sm font-bold">Email address<input required type="email" name="email" autoComplete="email" className="focus-ring h-12 rounded-xl border border-[#cad4ce] bg-white px-4 font-normal" /></label><label className="grid gap-2 text-sm font-bold">Password<input required type="password" name="password" autoComplete="current-password" className="focus-ring h-12 rounded-xl border border-[#cad4ce] bg-white px-4 font-normal" /></label>{params.error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{params.error === "recaptcha" ? "Please complete the security check." : "Those credentials could not be verified."}</p>}<RecaptchaWidget siteKey={process.env.RECAPTCHA_SITE_KEY} /><Button size="lg">Sign in</Button></form><p className="mt-6 text-center text-sm text-[#5f6f67]">New here? <Link className="font-bold text-[#123c31]" href="/signup">Create an account</Link></p>{process.env.SHOW_DEMO_CREDENTIALS === "true" && <div className="mt-8 rounded-xl bg-[#eef3e9] p-4 text-xs leading-5 text-[#5f6f67]"><strong className="text-[#123c31]">Local demo:</strong> learner@ailiteracy.local / ChangeMe123!</div>}</>;
}
