# Generated by Django 4.2.28 on 2026-03-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterclassregistration",
            name="location",
            field=models.CharField(
                choices=[("ABUJA", "Abuja"), ("ONLINE", "Online")],
                max_length=20,
            ),
        ),
    ]
