# Generated by Django 4.2.28 on 2026-03-19 01:48

from django.db import migrations, models


def convert_bootcamp_to_in_person(apps, schema_editor):
    MasterclassRegistration = apps.get_model("pages", "MasterclassRegistration")
    MasterclassRegistration.objects.filter(mode="BOOTCAMP").update(mode="IN_PERSON")


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_masterclassregistration_location"),
    ]

    operations = [
        migrations.RunPython(convert_bootcamp_to_in_person, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="masterclassregistration",
            name="mode",
            field=models.CharField(
                choices=[("IN_PERSON", "In-person"), ("ONLINE", "Online")],
                max_length=20,
            ),
        ),
    ]
