# Generated by Django 4.2.28 on 2026-03-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_remove_bootcamp_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsubmission",
            name="score",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
