# Generated by Django 4.2.28 on 2026-03-19 12:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_quizsubmission_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsubmission",
            name="share_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
